version: '3.8'

services:
  postgres:
    ports:
      - "5432:5432"
    image: postgres:latest
    restart: always
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: buyandsell
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 456
  keycloak:
    image: quay.io/keycloak/keycloak:22.0.4
    command: start-dev
    restart: unless-stopped
    depends_on:
      - postgres
    links:
      - postgres
    ports:
      - "9081:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin@1234
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/buyandsell
      KC_DB_SCHEMA: public
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: 456
      KC_DB_NAME: buyandsell
      KC_FEATURES: token-exchange,admin-fine-grained-authz
      KC_HOSTNAME: localhost
    volumes:
      - ./extensions:/opt/keycloak/providers/
  redis:
    image: redis:alpine3.14
    command: redis-server --requirepass redis
    ports:
      - "6379:6379"
  elasticsearch:
    image: elasticsearch:7.12.1
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - network.host=127.0.0.1
      - http.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
  pgsync:
    image: pgsync:latest
    build:
      context: ./docker/pgsync
      dockerfile: Dockerfile
    sysctls:
      - net.ipv4.tcp_keepalive_time=200
      - net.ipv4.tcp_keepalive_intvl=200
      - net.ipv4.tcp_keepalive_probes=5
    links:
      - postgres
      - elasticsearch
      - redis
    environment:
      PG_HOST: postgres
      POSTGRES_PORT: 5432
      PG_USER: postgres
      PG_PASSWORD: 456
      LOG_LEVEL: INFO
      ELASTICSEARCH_HOST: elasticsearch
      ELASTICSEARCH_PORT: 9200
      ELASTICSEARCH_SCHEME: http
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_AUTH: redis

  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.1
    container_name: kibana
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch