version: "3.8"
services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=buyandsell
      - POSTGRES_USER=buyandsell
      - POSTGRES_PASSWORD=buyandsell
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U buyandsell" ]
    volumes:
      - postgresvolume:/var/lib/postgresql/data
  keycloak:
    image: quay.io/keycloak/keycloak:22.0.4
    command: start-dev
    restart: unless-stopped
    depends_on:
      - postgres
    links:
      - postgres
    ports:
      - "9081:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/buyandsell
      KC_DB_SCHEMA: public
      KC_DB_USERNAME: buyandsell
      KC_DB_PASSWORD: buyandsell
      KC_DB_NAME: buyandsell
      KC_FEATURES: token-exchange,admin-fine-grained-authz
      KC_HOSTNAME: localhost
    volumes:
      - ./extensions:/opt/keycloak/providers/

volumes:
  postgresvolume: