logging:
  level:
    org:
      springframework:
        security: debug

server:
  port: 8085
spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://${JDBC_URL:localhost}:${JDBC_PORT:5432}/${DATABASE_NAME:buyandsell}
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:456}
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: false
    baseline-on-migrate: true
    baseline-version: 0
  mail:
    port: 587
    host: smtp.gmail.com
    username: testfortest891@gmail.com
    password: iabxmmbebumtizqt
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${keycloak.domain}/realms/${keycloak.realm}

app:
  name: SandBox task API
  api:
    title: Spring Boot APIs
    version: 1.0.0
    description: Spring Boot APIs description
    base-package: am.devvibes.buyandsell
    contact-name: Norayr Gharibyan
    contact-email: norayrgh@gmail.com
    swagger:
      enable: true


#keycloak:
#  realm: BuyAndSell
#  domain: localhost:8080
#  clientId: buy-and-sell-be
#  clientSecret: TjgE28OqkbR2laqeAI9GezLXkAlVj8cP
#  urls:
#    auth: http://${keycloak.domain}

keycloak:
  realm: buy-and-sell
  domain: localhost:9081
  adminClientId: buy-and-sell-client-id
  adminClientSecret: yZYSRo9cDdnmBR24VBJ51FEG1R3FqnuO
  urls:
    auth: http://${keycloak.domain}



