INSERT INTO description_entity (id, header, category_id)
VALUES
/*CAR*/
(1, 'SPECIFICATIONS', 1),
(2, 'ADDITIONAL_INFORMATION', 1),
(3, 'EXTERIOR', 1),
(4, 'INTERIOR', 1),

/*TRUCK*/
(5, 'SPECIFICATIONS',2),
(6, 'ADDITIONAL_INFORMATION', 2),

/*BUS*/
(7, 'SPECIFICATIONS',3),
(8, 'ADDITIONAL_INFORMATION', 3),

/*APARTMENT BUY*/
(9, 'BUILDING_INFORMATION',4),
(10, 'APARTMENT_INFORMATION', 4),

/*APARTMENT RENTAL*/
(11, 'BUILDING_INFORMATION',5),
(12, 'APARTMENT_INFORMATION', 5),
(13, 'HOUSE_RULES', 5),
(14, 'DEAL_TERMS', 5),

/*HOUSE BUY*/
(15, 'HOUSE_INFORMATION',6),
(16, 'LOT_INFORMATION', 6),

/*HOUSE RENTAL*/
(17, 'HOUSE_INFORMATION',7),
(18, 'LOT_INFORMATION', 7),
(19, 'HOUSE_RULES',7),
(20, 'DEAL_TERMS',7),

/*COMMERCIAL BUY*/
(21, 'ADDITIONAL_INFORMATION', 8),

/*COMMERCIAL RENTAL*/
(22, 'ADDITIONAL_INFORMATION', 9),
(23, 'DEAL_TERMS',9),

/*GARAGE AND PARKING BUY*/
(24, 'ADDITIONAL_INFORMATION', 10),

/*GARAGE AND PARKING RENTAL*/
(25, 'ADDITIONAL_INFORMATION', 11),
(26, 'DEAL_TERMS', 11),

/*LAND BUY*/
(27, 'ADDITIONAL_INFORMATION', 12),

/*LAND RENTAL*/
(28, 'ADDITIONAL_INFORMATION', 13),
(29, 'DEAL_TERMS', 13),

/*NEW CONSTRUCTION APARTMENT*/
(30, 'BUILDING_INFORMATION',14),
(31, 'APARTMENT_INFORMATION', 14),
(32, 'STAGE_OF_PREPARATION', 14),
(33, 'DEAL_TERMS', 14),

/*NEW CONSTRUCTION HOUSE*/
(34, 'HOUSE_INFORMATION',15),
(35, 'LOT_INFORMATION', 15),
(36, 'STAGE_OF_PREPARATION', 15),
(37, 'DEAL_TERMS', 15),

/*APARTMENT DAILY RENTAL*/
(38, 'BUILDING_INFORMATION',16),
(39, 'APARTMENT_INFORMATION', 16),
(40, 'HOUSE_RULES',16),

/*HOUSE DAILY RENTAL*/
(41, 'HOUSE_INFORMATION',17),
(42, 'LOT_INFORMATION', 17),
(43, 'HOUSE_RULES',17),

/*MOBILE PHONE*/
(44,'SPECIFICATIONS',18),

/*NOTEBOOK*/
(45, 'SPECIFICATIONS', 19),

/*COMPUTER*/
(46, 'SPECIFICATIONS', 20),

/*SMART WATCH*/
(47, 'SPECIFICATIONS', 21),

/*TABLET*/
(48, 'SPECIFICATIONS', 22),

/*TV*/
(49, 'SPECIFICATIONS', 23),

/*GAMING CONSOLE*/
(50, 'SPECIFICATIONS', 24),

/*HEADPHONE*/
(51, 'SPECIFICATIONS', 25),

/*COMPUTER AND NOTEBOOK PARTS*/
(52, 'SPECIFICATIONS', 26),

/*PHOTO AND VIDEO CAMERA*/
(53, 'SPECIFICATIONS', 27),

/*COMPUTER GAMES*/
(54, 'SPECIFICATIONS', 28),

/*SMART HOME ACCESSORIES*/
(55, 'SPECIFICATIONS', 29),

/*WASHER*/
(56, 'SPECIFICATIONS', 30),

/*CLOTHES DRYER*/
(57, 'SPECIFICATIONS', 31),

/*IRON AND ACCESSORIES*/
(58, 'SPECIFICATIONS', 32),

/*REFRIGERATOR*/
(59, 'SPECIFICATIONS', 33),

/*FREEZER*/
(60, 'SPECIFICATIONS', 34),

/*DISHWASHER*/
(61, 'SPECIFICATIONS', 35),

/*MICROWAVE*/
(62, 'SPECIFICATIONS', 36),

/*STOVE*/
(63, 'SPECIFICATIONS', 37),

/*COFFEE MAKER AND ACCESSORIES*/
(64, 'SPECIFICATIONS', 38),

/*TEA_KETTLES*/
(65, 'SPECIFICATIONS', 39),

/*RANGE_HOODS*/
(66, 'SPECIFICATIONS', 40),

/*VACUUM_CLEANERS*/
(67, 'SPECIFICATIONS', 41),

/*ROBOTIC_VACUUMS*/
(68, 'SPECIFICATIONS', 42),

/*FLOOR_WASHERS*/
(69, 'SPECIFICATIONS', 43),

/*AIR_CONDITIONERS*/
(70, 'SPECIFICATIONS', 44),

/*WATER_HEATERS*/
(71, 'SPECIFICATIONS', 45),

/*AIR_PURIFIERS_AND_HUMIDIFIERS*/
(72, 'SPECIFICATIONS', 46),

/*COMPUTERS_PERIPHERALS*/
(73, 'SPECIFICATIONS', 47),

/*AUDIO_PLAYERS_AND_STEREOS*/
(74, 'ADDITIONAL_INFORMATION', 48),
(75, 'SPECIFICATIONS', 48),

/*QUADCOPTERS_AND_DRONES*/
(76, 'SPECIFICATIONS', 49),

/*SOFAS_AND_ARMCHAIRS*/
(77, 'SPECIFICATIONS', 50),

/*STORAGE*/
(78, 'SPECIFICATIONS', 51),

/*TABLES_AND_CHAIRS*/
(79, 'SPECIFICATIONS', 52),

/*BEDROOM_FURNITURE*/
(80, 'SPECIFICATIONS', 53),

/*KITCHEN_FURNITURE*/
(81, 'SPECIFICATIONS', 54),

/*GARDEN_FURNITURE*/
(82, 'SPECIFICATIONS', 55),

/*BARBECUE_AND_ACCESSORIES*/
(83, 'SPECIFICATIONS', 56),

/*GARDEN_DECOR*/
(84, 'SPECIFICATIONS', 57),

/*GARDEN_ACCESSORIES*/
(85, 'SPECIFICATIONS', 58),

/*LIGHTING*/
(86, 'SPECIFICATIONS', 59),

/*TEXTILES*/
(87, 'SPECIFICATIONS', 60),

/*RUGS*/
(88, 'SPECIFICATIONS', 61),

/*INTERIOR_DECORATION*/
(89, 'SPECIFICATIONS', 62),

/*TABLEWARE*/
(90, 'SPECIFICATIONS', 63),

/*COOKING_AND_BAKING*/
(91, 'SPECIFICATIONS', 64),

/*KITCHEN_ACCESSORIES*/
(92, 'SPECIFICATIONS', 65),

/*BATHROOM_ACCESSORIES*/
(93, 'SPECIFICATIONS', 66),

/*VIDEO_SURVEILLANCE*/
(94, 'SPECIFICATIONS', 67),

/*CAR_PARTS*/
(95, 'SPECIFICATIONS', 68),

/*WHEELS_AND_TIRES*/
(96, 'SPECIFICATIONS', 69),

/*RIMS_AND_HUB_CAPS*/
(97, 'SPECIFICATIONS', 70),

/*CAR_BATTERIES*/
(98, 'SPECIFICATIONS', 71),

/*GAS_EQUIPMENT*/
(99, 'SPECIFICATIONS', 72),

/*OILS_AND_CHEMICALS*/
(100, 'SPECIFICATIONS', 73),

/*CAR_ACCESSORIES*/
(101, 'SPECIFICATIONS', 74),

/*CAR_ELECTRONICS*/
(102, 'SPECIFICATIONS', 75),

/*CAR_AUDIO_AND_VIDEO*/
(103, 'SPECIFICATIONS', 76),

/*PERSONAL_TRANSPORTATION*/
(104, 'SPECIFICATIONS', 77),

/*ATVS_AND_SNOWMOBILES*/
(105, 'SPECIFICATIONS', 78),

/*BOATS_AND_WATER_TRANSPORT*/
(106, 'SPECIFICATIONS', 79),

/*TRAILERS_AND_BOOTHS*/
(107, 'SPECIFICATIONS', 80),
(108, 'BUILDING_INFORMATION',80),

/*EVENT_VENUES_RENTAL*/
(109, 'ADDITIONAL_INFORMATION', 81),
(110, 'HOUSE_RULES', 81)
ON CONFLICT (id) DO NOTHING;