version: '3.1'
services:
  buy_and_sell:
    build:
      context: ../
      dockerfile: Dockerfile
    depends_on:
      - PostgreSQL
    ports:
      - "8080:8080"
  PostgreSQL:
    image: postgres
    user: root
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=0710
      - POSTGRES_USER=postgres
      - POSTGRES_DB=buyandsell
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5